### PR TITLE
task/125-throw-exception-from-the-repository-and-dont-return-null

### LINKED ISSUE #125: throw exception from the repository and don't return null
- should throw exception not returning null 
- mapping from null to exception should be in the repository (it's ok to return null from data source) but should throwing exception when getting null result
- Audit also returns null in the use case refactor to throw exception from there Audit repository 
- check any other useCase that return null , throw exception from the repositories

### PR DESCRIPTION
**Pull request by mostafa-n3ma**

### CODE REVIEW

File: src/main/kotlin/data/dataSource/audit/MongoAuditDataSource.kt [hunk 1]
```diff
@@ -13,6 +13,11 @@ class MongoAuditDataSource(
     }
 
     override suspend fun getAllAudit(): List<AuditDto> {
-        return auditCollection.find().toList()
+        return try {
```
Comment (NadeenRR) [inline src/main/kotlin/data/dataSource/audit/MongoAuditDataSource.kt]: Why use try catch here, but remove from CsvAuditDataSource?

File: src/main/kotlin/domain/usecases/AddAuditUseCase.kt [hunk 2]
```diff
@@ -33,13 +33,11 @@ class AddAuditUseCase(
             userId = userId,
             timestamp = timeStamp
         )
-        val result = auditRepository.addAudit(newAudit)
-
-        return when (result) {
-            true -> newAudit
-            false -> null
+        try {
```
Comment (NadeenRR) [inline src/main/kotlin/domain/usecases/AddAuditUseCase.kt:36]: why use try catch in the use case?

File: src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt [hunk 3]
```diff
@@ -55,16 +55,16 @@ class CsvAuditDataSourceTest {
...
-    fun `add audit should return false when changing file writing permission`() = runTest {
-        //given
-        file.setReadOnly()
-        //when
-        val result = dataSource.addAudit(DummyTaskAuditDto)
-
-        //then
-        assertThat(result).isFalse()
-    }
+//    @Test
```
Comment (NadeenRR) [inline src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt]: Ya rab falah ma yshofe

**Review by NadeenRR — COMMENTED** [review]
Great work Mustafa!

File: src/main/kotlin/data/dataSource/audit/MongoAuditDataSource.kt (hunk 1 above)
Comment (mostafa-n3ma) [reply src/main/kotlin/data/dataSource/audit/MongoAuditDataSource.kt]: noted and and i did removed it

File: src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt (hunk 3 above)
Comment (mostafa-n3ma) [reply src/test/kotlin/data/dataSource/audit/CsvAuditDataSourceTest.kt]: 😅 gone

File: src/main/kotlin/domain/usecases/AddAuditUseCase.kt (hunk 2 above)
Comment (mostafa-n3ma) [reply src/main/kotlin/domain/usecases/AddAuditUseCase.kt:36]: when adding audit it is emportent to record any failler happened in the data source so I try to logg it here 
and it don't have a cli to add audit we use this us case in other use cases like add user or delete task 
so we handle any audit data source specific exceptions here

**Review by NadeenRR — APPROVED** [review]
Approve
